version: "3"

networks:
  loki:

services:

  loki:
    image: grafana/loki:master
    ports:
      - "3100:3100"
    volumes:
      - $PWD/loki:/etc/loki
    command: -config.file=/etc/loki/loki-local-config.yaml
    networks:
      - loki

  promtail:
    image: grafana/promtail:master
    volumes:
      - $PWD/promtail:/etc/promtail
      - /var/log:/var/log
    command:
      -config.file=/etc/promtail/promtail-docker-config.yaml
    networks:
      - loki

  prometheus-server:
    container_name: prometheus
    image: prom/prometheus
    volumes:
      - ./prometheus/config:/etc/prometheus/
        # - prometheus_data:/data:rw
      - ./prometheus/data/:/prometheus/data/:rw
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=365d'
    ports:
      - 9090:9090
    links:
      - cadvisor:cadvisor
      - node-exporter:node-exporter
    restart: always
    networks:
      - loki
    restart: always

  node-exporter:
    container_name: node-exporter
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command: 
      - '--path.procfs=/host/proc' 
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
      - 9100:9100
    networks:
      - loki
    restart: always

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports: 
      - 3000:3000
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/plugins/:/var/lib/grafana/plugins/
    restart: always
    environment:
      GF_EXPLORE_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: "/etc/grafana/provisioning/dashboards/tasmota-monitoring.json"
      GF_SERVER_DOMAIN: "grafana"
    networks: 
      - loki

  cadvisor:
    container_name: cadvisor
    image: zcube/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    ports:
      - 8081:8080
    networks:
      - loki
    devices:
      - /dev/kmsg
    privileged: true
    command:
      - '--docker_only'
      - '--disable_metrics=disk,diskIO,tcp,udp,percpu,sched,process'
      - '--housekeeping_interval=10s'
    restart: always

#volumes:
#  prometheus_data:
