#my global config
global:
  scrape_interval:     5s # By default, scrape targets every 15 seconds.
  evaluation_interval: 5s # By default, scrape targets every 15 seconds.
# scrape_timeout is set to the global default (10s).
# Attach these extra labels to all timeseries collected by this Prometheus instance.
#labels:
#  monitor: 'codelab-monitor'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
#rule_files:
#- '/etc/prometheus/alert.rules'
# - "second.rules"

scrape_configs:
  - job_name: "cAdvisor"
    static_configs:
    - targets: ["cadvisor:8080"]
      labels:
        group: 'dev'
  - job_name: "node-exporter"
    static_configs:
    - targets: ["node-exporter:9100"]
      labels:
        group: 'dev'
  - job_name: "prometheus"
    static_configs:
    - targets: ["prometheus:9090"]
      labels:
        group: 'dev'
