#my global config
global:
  scrape_interval:     30s # By default, scrape targets every 15 seconds.
  evaluation_interval: 5s # By default, scrape targets every 15 seconds.
# scrape_timeout is set to the global default (10s).
# Attach these extra labels to all timeseries collected by this Prometheus instance.
#labels:
#  monitor: 'codelab-monitor'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
#rule_files:
#- '/etc/prometheus/alert.rules'
# - "second.rules"

scrape_configs:
  - job_name: "cAdvisor"
    static_configs:
    - targets: ["cadvisor:8080"]
      labels:
        group: 'dev'
    scrape_interval: 5s
  - job_name: "node-exporter"
    static_configs:
    - targets: ["node-exporter:9100"]
      labels:
        group: 'dev'
    scrape_interval: 5s
  - job_name: "prometheus"
    static_configs:
    - targets: ["prometheus:9090"]
      labels:
        group: 'dev'
    scrape_interval: 5s
  - job_name: "promtail"
    static_configs:
    - targets: ["loki:3100"]
      labels:
        group: 'dev'
    scrape_interval: 5s
  - job_name: 'tasmotas'
    static_configs:
      - targets:
        - '10.2.4.13:80'
        labels:
          hostname: 'FamilyLights'
          room: 'Family Room'
          location: 'Inside'
          floor: 'First'
      - targets:
        - '10.2.4.14:80'
        labels:
          hostname: 'FamilyFan'
          room: 'Family Room'
          location: 'Inside'
          floor: 'First'
      - targets:
        - '10.2.4.16:80'
        labels:
          hostname: 'LilyHall'
          room: 'Upstairs Hall'
          location: 'Inside'
          floor: 'Second'
      - targets:
        - '10.2.4.17:80'
        labels:
          hostname: 'EntryCans_C1'
          room: 'Main Hall'
          location: 'Inside'
          floor: 'First'
      - targets:
        - '10.2.4.18:80'
        labels:
          hostname: 'EntryCans'
          room: 'Main Entry'
          location: 'Inside'
          floor: 'First'
      - targets:
        - '10.2.4.19:80'
        labels:
          hostname: 'EntryCans_C2'
          room: 'Upstairs Hall'
          location: 'Inside'
          floor: 'Second'
      - targets:
        - '10.2.4.20:80'
        labels:
          hostname: 'KidsSink'
          room: 'Upstairs Bathroom'
          location: 'Inside'
          floor: 'Second'
      - targets:
        - '10.2.4.21:80'
        labels:
          hostname: 'AustinHall'
          room: 'Upstairs Hall'
          location: 'Inside'
          floor: 'Second'
      - targets:
        - '10.2.4.22:80'
        labels:
          hostname: 'DadsLights'
          room: 'Dads Room'
          location: 'Inside'
          floor: 'Second'
      - targets:
        - '10.2.4.23:80'
        labels:
          hostname: 'LilyHall_C1'
          room: 'Upstairs Hall'
          location: 'Inside'
          floor: 'Second'
      - targets:
        - '10.2.4.24:80'
        labels:
          hostname: 'PorchLights'
          room: 'Main Entry'
          location: 'Inside'
          floor: 'First'
      - targets:
        - '10.2.4.26:80'
        labels:
          hostname: 'AustinHall_C1'
          room: 'Upstairs Hall'
          location: 'Inside'
          floor: 'Second'
      - targets:
        - '10.2.4.27:80'
        labels:
          hostname: 'LilyHall_C2'
          room: 'Upstairs Hall'
          location: 'Inside'
          floor: 'Second'
      - targets:
        - '10.2.4.28:80'
        labels:
          hostname: 'MainHall_C1'
          room: 'Main Hall'
          location: 'Inside'
          floor: 'First'
      - targets:
        - '10.2.4.29:80'
        labels:
          hostname: 'MainHall'
          room: 'Main Hall'
          location: 'Inside'
          floor: 'First'
      - targets:
        - '10.2.4.30:80'
        labels:
          hostname: 'MainHall_C2'
          room: 'Main Hall'
          location: 'Inside'
          floor: 'First'
      - targets:
        - '10.2.4.31:80'
        labels:
          hostname: 'KitchenCans'
          room: 'Main Hall'
          location: 'Inside'
          floor: 'First'
      - targets:
        - '10.2.4.32:80'
        labels:
          hostname: 'KitchenSink'
          room: 'Main Hall'
          location: 'Inside'
          floor: 'First'
      - targets:
        - '10.2.4.33:80'
        labels:
          hostname: 'KitchenSink_C1'
          room: 'Kitchen'
          location: 'Inside'
          floor: 'First'
      - targets:
        - '10.2.4.34:80'
        labels:
          hostname: 'KitchenCans_C1'
          room: 'Kitchen'
          location: 'Inside'
          floor: 'First'
      - targets:
        - '10.2.4.35:80'
        labels:
          hostname: 'PowderHall'
          room: 'Main Hall'
          location: 'Inside'
          floor: 'First'
      - targets:
        - '10.2.4.36:80'
        labels:
          hostname: 'StudyLights'
          room: 'Study'
          location: 'Inside'
          floor: 'First'
      - targets:
        - '10.2.4.37:80'
        labels:
          hostname: 'LibraryLights'
          room: 'Library'
          location: 'Inside'
          floor: 'First'
      - targets:
        - '10.2.4.41:80'
        labels:
          hostname: 'EveLights'
          room: 'Front Entry'
          location: 'Inside'
          floor: 'First'
      - targets:
        - '10.2.4.42:80'
        labels:
          hostname: 'PowderFan'
          room: 'Powder Bathroom'
          location: 'Inside'
          floor: 'First'
      - targets:
        - '10.2.4.43:80'
        labels:
          hostname: 'StudyFan'
          room: 'Study'
          location: 'Inside'
          floor: 'First'
      - targets:
        - '10.2.4.44:80'
        labels:
          hostname: 'PowderLights'
          room: 'Powder Bathroom'
          location: 'Inside'
          floor: 'First'
      - targets:
        - '10.2.4.47:80'
        labels:
          hostname: 'ChristmasPackage'
          room: 'Main Entry'
          location: 'Inside'
          floor: 'First'
      - targets:
        - '10.2.4.48:80'
        labels:
          hostname: 'BasementLights'
          room: 'Basement'
          location: 'Inside'
          floor: 'Basement'
      - targets:
        - '10.2.4.50:80'
        labels:
          hostname: 'DiningLights'
          room: 'Dining'
          location: 'Inside'
          floor: 'First'
      - targets:
        - '10.2.4.51:80'
        labels:
          hostname: 'PatioLights'
          room: 'Dinnig'
          location: 'Inside'
          floor: 'First'
      - targets:
        - '10.2.4.52:80'
        labels:
          hostname: 'GarageLights'
          room: 'Garage'
          location: 'Garage'
          floor: 'First'
      - targets:
        - '10.2.4.53:80'
        labels:
          hostname: 'ExteriorGarageLights'
          room: 'Garage'
          location: 'Garage'
          floor: 'First'
      - targets:
        - '10.2.4.54:80'
        labels:
          hostname: 'KidsBathroomFan'
          room: 'Kids Bathroom'
          location: 'Inside'
          floor: 'Second'
      - targets:
        - '10.2.4.67:80'
        labels:
          hostname: 'ExteriorSide'
          room: 'Garage'
          location: 'Garage'
          floor: 'First'
      - targets:
        - '10.2.4.68:80'
        labels:
          hostname: 'GarageLights_C1'
          room: 'Garage'
          location: 'Garage'
          floor: 'First'
      - targets:
        - '10.2.4.72:80'
        labels:
          hostname: 'KidsToilet'
          room: 'Kids Bathroom'
          location: 'Inside'
          floor: 'Second'
      - targets:
        - '10.2.4.73:80'
        labels:
          hostname: 'KidsShower'
          room: 'Kids Bathroom'
          location: 'Inside'
          floor: 'Second'
      - targets:
        - '10.2.4.83:80'
        labels:
          hostname: 'EntryChandelier'
          room: 'Main Entry'
          location: 'Inside'
          floor: 'First'
      # - targets:
      #   - '10.2.4.90:80'
      #   labels:
      #     hostname: 'KitchenTable'
      #     room: 'Kitchen'
      - targets:
        - '10.2.4.91:80'
        labels:
          hostname: 'EndTable'
          room: 'Family Room'
          location: 'Inside'
          floor: 'First'
      - targets:
        - '10.2.4.92:80'
        labels:
          hostname: 'IslandDecorations'
          room: 'Kitchen'
          location: 'Inside'
          floor: 'First'
      # - targets:
      #   - '10.2.4.93:80'
      #   labels:
      #     hostname: 'ChristmasRailing'
      #     room: 'Library'
      #     location: 'Inside'
      #     floor: 'First'
      - targets:
        - '10.2.4.96:80'
        labels:
          hostname: 'MediaRemote'
          room: 'Family Room'
          location: 'Inside'
          floor: 'First'
      - targets:
        - '10.2.4.98:80'
        labels:
          hostname: 'BuffetDecor'
          room: 'Main Hall'
          location: 'Inside'
          floor: 'First'
      - targets:
        - '10.2.4.99:80'
        labels:
          hostname: 'EntryDecorations'
          room: 'Main Entry'
          location: 'Inside'
          floor: 'First'
      - targets:
        - '10.2.4.100:80'
        labels:
          hostname: 'RailingLights'
          room: 'Upstairs Hall'
          location: 'Inside'
          floor: 'Second'
      - targets:
        - '10.2.4.101:80'
        labels:
          hostname: 'CurtainLights'
          room: 'Family Room'
          location: 'Inside'
          floor: 'First'
      - targets:
        - '10.2.4.103:80'
        labels:
          hostname: 'FirePlace'
          room: 'Family Room'
          location: 'Inside'
          floor: 'First'
      - targets:
        - '10.2.4.104:80'
        labels:
          hostname: 'Blower'
          room: 'Family Room'
          location: 'Inside'
          floor: 'First'
      - targets:
        - '10.2.4.105:80'
        labels:
          hostname: 'LeftMantle'
          room: 'Family Room'
          location: 'Inside'
          floor: 'First'
      # - targets:
      #   - '10.2.4.111:80'
      #   labels:
      #     hostname: 'FrontTree'
      #     room: 'Library'
      #     location: 'Inside'
      #     floor: 'First'
      - targets:
        - '10.2.4.113:80'
        labels:
          hostname: 'DadsFan'
          room: 'Dads Room'
          location: 'Inside'
          floor: 'Second'
      - targets:
        - '10.2.4.116:80'
        labels:
          hostname: 'MantleDecor'
          room: 'Family Room'
          location: 'Inside'
          floor: 'First'
      - targets:
        - '10.2.4.117:80'
        labels:
          hostname: 'DadsLamp'
          room: 'Dads Room'
          location: 'Inside'
          floor: 'Second'
    scrape_interval: 120s
  - job_name: 'sensor_devices'
    static_configs:
      - targets:
        - '10.2.4.102:80'
        labels:
          hostname: 'GarageLamp'
          room: 'Garage'
          location: 'Garage'
          floor: 'First'
      - targets:
        - '10.2.4.109:80'
        labels:
          hostname: 'DadsTest'
          room: 'Dads Room'
          location: 'Inside'
          floor: 'Second'
      - targets:
        - '10.2.4.112:80'
        labels:
          hostname: 'RetroPi'
          room: 'Family Room'
          location: 'Inside'
          floor: 'First'
      - targets:
        - '10.2.4.114:80'
        labels:
          hostname: 'ElectricFence'
          room: 'Outside'
          location: 'Outside'
          floor: 'Outside'
      - targets:
        - '10.2.4.118:80'
        labels:
          hostname: 'InternetRouter'
          room: 'Utility Closet'
          location: 'Inside'
          floor: 'Basement'
      - targets:
        - '10.2.4.119:80'
        labels:
          hostname: 'WorkspaceMonitor'
          room: 'Basement Office'
          location: 'Inside'
          floor: 'Basement'
    scrape_interval: 60s
  - job_name: 'always_on'
    static_configs:
      - targets:
        - '10.2.4.39:80'
        labels:
          hostname: 'DeepFreeze'
          room: 'Garage'
          location: 'Garage'
          floor: 'First'
      - targets:
        - '10.2.4.45:80'
        labels:
          hostname: 'GarageFreezer'
          room: 'Garage'
          location: 'Garage'
          floor: 'First'
      - targets:
        - '10.2.4.49:80'
        labels:
          hostname: 'GarageFridge'
          room: 'Garage'
          location: 'Garage'
          floor: 'First'
      - targets:
        - '10.2.4.60:80'
        labels:
          hostname: 'DadsWorkspace'
          room: 'Basement Office'
          location: 'Inside'
          floor: 'Basement'
      - targets:
        - '10.2.4.63:80'
        labels:
          hostname: 'ComputerMedia'
          room: 'Basement Office'
          location: 'Inside'
          floor: 'Basement'
      - targets:
        - '10.2.4.66:80'
        labels:
          hostname: 'NetworkEquipment'
          room: 'Utility Closet'
          location: 'Inside'
          floor: 'Basement'
      - targets:
        - '10.2.4.70:80'
        labels:
          hostname: 'KitchenFridge'
          room: 'Kitchen'
          location: 'Inside'
          floor: 'First'
      - targets:
        - '10.2.4.71:80'
        labels:
          hostname: 'HotTub'
          room: 'Outside'
          location: 'Outside'
          floor: 'Outside'
    scrape_interval: 30s
  - job_name: 'power_monitors'
    static_configs:
      - targets:
        - '10.2.4.38:80'
        labels:
          hostname: 'ComputerAustin'
          room: 'Study'
          location: 'Inside'
          floor: 'First'
      - targets:
        - '10.2.4.40:80'
        labels:
          hostname: 'Unused1'
          room: 'Portable'
          location: 'Inside'
          floor: 'First'
      - targets:
        - '10.2.4.46:80'
        labels:
          hostname: 'LaptopCharger'
          room: 'Portable'
          location: 'Inside'
          floor: 'First'
      - targets:
        - '10.2.4.55:80'
        labels:
          hostname: 'Unused2'
          room: 'Portable'
          location: 'Inside'
          floor: 'First'
      - targets:
        - '10.2.4.56:80'
        labels:
          hostname: 'GroundDecor'
          room: 'Outside'
          location: 'Outside'
          floor: 'Outside'
      # - targets:
      #   - '10.2.4.57:80'
      #   labels:
      #     hostname: 'ElectricFence'
      #     room: 'Outside'
      - targets:
        - '10.2.4.58:80'
        labels:
          hostname: 'ComputerLily'
          room: 'Study'
          location: 'Inside'
          floor: 'First'
      - targets:
        - '10.2.4.59:80'
        labels:
          hostname: 'MainTV'
          room: 'Family Room'
          location: 'Inside'
          floor: 'First'
      - targets:
        - '10.2.4.61:80'
        labels:
          hostname: 'MasterTV'
          room: 'Master Bedroom'
          location: 'Inside'
          floor: 'First'
      - targets:
        - '10.2.4.62:80'
        labels:
          hostname: 'TopChristmas'
          room: 'Outside'
          location: 'Outside'
          floor: 'Outside'
      # - targets:
      #   - '10.2.4.64:80'
      #   labels:
      #     hostname: 'LilyFan'
      #     room: ''
      # - targets:
      #   - '10.2.4.65:80'
      #   labels:
      #     hostname: 'FrontTree'
      #     room: 'Family Room'
      - targets:
        - '10.2.4.69:80'
        labels:
          hostname: 'PetLights'
          room: 'Austins Room'
          location: 'Inside'
          floor: 'Second'
      - targets:
        - '10.2.4.89:80'
        labels:
          hostname: 'BottomChristmas'
          room: 'Outside'
          location: 'Outside'
          floor: 'Outside'
    scrape_interval: 60s
