{
 "title": "Tasmota Statistics",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "yaxes": [
    { "format": "fahrenheit" }
   ],
   "targets": [
    {
     "expr": "((tasmotaglobal_temperature_celsius * 9/5) + 32)",
     "legendFormat": "{{hostname}}-{{instance}}"
    }
   ]
  },
  {
   "title": "Signal",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "yaxes": [
    { "format": "dB" }
   ],
   "targets": [
    {
     "expr": "tasmota_wifi_station_signal_dbm",
     "legendFormat": "{{location}}"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    { "expr": "tasmotaglobal_humidity", "legendFormat": "{{hostname}}-{{instance}}" }
   ]
  },
  {
   "title": "Pressure",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "yaxes": [
    { "format": "pressurehpa" }
   ],
   "targets": [
    { "expr": "tasmotaglobal_pressure_hpa", "legendFormat": "{{hostname}}-{{instance}}" }
   ]
  },
  {
   "title": "Active Watts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    { "expr": "energy_power_active_watts", "legendFormat": "{{hostname}}-{{instance}}" }
   ]
  },
  {
   "title": "Daily Kilowatts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "yaxes": [
    { "format": "kwatt" }
   ],
   "targets": [
    { "expr": "energy_power_kilowatts_daily", "legendFormat": "{{hostname}}-{{instance}}" }
   ]
  },
  {
   "title": "Active Amps",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "voltamp" } },
   "yaxes": [
    { "format": "voltamp" }
   ],
   "targets": [
    { "expr": "energy_current_amperes", "legendFormat": "{{hostname}}-{{instance}}" }
   ]
  },
  {
   "title": "Total Kilowatts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "yaxes": [
    { "format": "kwatt" }
   ],
   "targets": [
    { "expr": "energy_power_kilowatts_total", "legendFormat": "{{hostname}}-{{instance}}" }
   ]
  },
  {
   "title": "Voltage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "voltamp" } },
   "yaxes": [
    { "format": "voltamp" }
   ],
   "targets": [
    { "expr": "energy_voltage_volts", "legendFormat": "{{hostname}}-{{instance}}" }
   ]
  },
  {
   "title": "Uptime",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "tasmota_uptime_seconds", "legendFormat": "{{hostname}}-{{instance}}" }
   ]
  }
 ]
}