{
 "title": "Tasmota Monitoring",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "yaxes": [
    { "format": "fahrenheit" }
   ],
   "targets": [
    {
     "expr": "((tasmotaglobal_temperature_celsius{job=\"sensor_devices\"} * 9/5) + 32)",
     "legendFormat": "{{hostname}}-{{instance}}"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "yaxes": [
    { "format": "pressurehpa" }
   ],
   "targets": [
    {
     "expr": "tasmotaglobal_pressure_hpa{job=\"sensor_devices\"}",
     "legendFormat": "{{hostname}}-{{instance}}"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    {
     "expr": "tasmotaglobal_humidity{job=\"sensor_devices\"}",
     "legendFormat": "{{hostname}}-{{instance}}"
    }
   ]
  },
  {
   "title": "Daily Kilowatts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "yaxes": [
    { "format": "kwatt" }
   ],
   "targets": [
    {
     "expr": "energy_power_kilowatts_daily{job=\"always_on\"}",
     "legendFormat": "{{hostname}}-{{instance}}"
    },
    {
     "expr": "energy_power_kilowatts_daily{job=\"power_monitors\"}",
     "legendFormat": "{{hostname}}-{{instance}}"
    }
   ]
  },
  {
   "title": "Active Watts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "energy_power_active_watts{job=\"always_on\"}",
     "legendFormat": "{{hostname}}-{{instance}}"
    },
    {
     "expr": "energy_power_active_watts{job=\"power_monitors\"}",
     "legendFormat": "{{hostname}}-{{instance}}"
    }
   ]
  },
  {
   "title": "Active Amps",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "voltamp" } },
   "yaxes": [
    { "format": "voltamp" }
   ],
   "targets": [
    {
     "expr": "energy_current_amperes{job=\"always_on\"}",
     "legendFormat": "{{hostname}}-{{instance}}"
    },
    {
     "expr": "energy_current_amperes{job=\"power_monitors\"}",
     "legendFormat": "{{hostname}}-{{instance}}"
    }
   ]
  },
  {
   "title": "Critical Devices Online",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "Up",
     "displayAliasType": "Always",
     "displayType": "Annotation",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "up{job=\"always_on\"}",
     "legendFormat": "{{hostname}}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Critical Devices Online",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregation": "Last",
     "alias": "Up",
     "displayAliasType": "Always",
     "displayType": "Annotation",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "avg_over_time(up{job=\"always_on\"}[10m])",
     "legendFormat": "{{hostname}}-{{instance}}",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "expr": "avg_over_time(up{location=\"Outside\"}[10m])",
     "legendFormat": "{{hostname}}-{{instance}}"
    },
    {
     "expr": "avg_over_time(up{hostname=\"WorkspaceMonitor\"}[10m])",
     "legendFormat": "{{hostname}}-{{instance}}"
    }
   ]
  },
  {
   "title": "No Voltage Draw",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt", "label": "Max Watts Over Time" }
   ],
   "targets": [
    {
     "aggregation": "Last",
     "alias": "Up",
     "displayAliasType": "Always",
     "displayType": "Annotation",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "max_over_time(energy_power_active_watts{hostname=\"GarageFreezer\"}[5m])",
     "legendFormat": "{{hostname}}-{{instance}}",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "alias": "Up",
     "displayAliasType": "Always",
     "displayType": "Annotation",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "max_over_time(energy_power_active_watts{hostname=\"KitchenFridge\"}[5m])",
     "legendFormat": "{{hostname}}-{{instance}}",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "alias": "Up",
     "displayAliasType": "Always",
     "displayType": "Annotation",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "max_over_time(energy_power_active_watts{hostname=\"GarageFridge\"}[5m])",
     "legendFormat": "{{hostname}}-{{instance}}",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "alias": "Up",
     "displayAliasType": "Always",
     "displayType": "Annotation",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "max_over_time(energy_power_active_watts{hostname=\"GarageFreezer\"}[5m])",
     "legendFormat": "{{hostname}}-{{instance}}",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "alias": "Up",
     "displayAliasType": "Always",
     "displayType": "Annotation",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "max_over_time(energy_power_active_watts{hostname=\"DeepFreeze\"}[24h])",
     "legendFormat": "{{hostname}}-{{instance}}",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "expr": "avg_over_time(energy_power_active_watts{hostname=\"HotTub\"}[10m])",
     "legendFormat": "{{hostname}}-{{instance}}"
    }
   ]
  },
  {
   "title": "Hot Tub Timed Out",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(energy_power_active_watts{hostname=\"HotTub\"}[10m])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Energy Cost, Total Previous Day",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "expr": "tasmota_sensors_yesterday_*.105959",
     "legendFormat": "{{hostname}}-{{instance}}"
    }
   ]
  }
 ]
}